name: Build and Check
description: Build and check the esp-hal and esp-lp-hal packages for a specified device
inputs:
  device:
    description: "Device SOC"
    required: true
  target:
    description: "Target"
    required: true
  toolchain:
    description: "Toolchain channel"
    required: true
runs:
  using: "composite"
  steps:
    - name: xtask ci
      shell: bash
      run: cargo ${{ inputs.toolchain }} xtask ci ${{ inputs.device }}
