[package]
name          = "esp-config"
version       = "0.3.1"
edition       = "2024"
rust-version  = "1.85.0"
description   = "Configure projects using esp-hal and related packages"
documentation = "https://docs.espressif.com/projects/rust/esp-config/latest/"
repository    = "https://github.com/esp-rs/esp-hal"
license       = "MIT OR Apache-2.0"

[lib]
bench = false
test  = true

[[bin]]
name = "esp-config"
required-features = ["tui"]

[dependencies]
document-features = "0.2.11"

# used by the `build` and `tui` feature
serde = { version = "1.0.197", features = ["derive"], optional = true }
serde_json = { version = "1.0.0", features = ["arbitrary_precision"], optional = true }

# used by the `tui` feature
clap            = { version = "4.5.32", features = ["derive"], optional = true }
crossterm       = { version = "0.28.1", optional = true }
env_logger      = { version = "0.11.7", optional = true }
log             = { version = "0.4.26", optional = true }
ratatui         = { version = "0.29.0", features = ["crossterm", "unstable"], optional = true }
toml_edit       = { version = "0.22.26", optional = true }
tui-textarea    = { version = "0.7.0", optional = true }
walkdir         = { version = "2.5.0", optional = true }

[dev-dependencies]
temp-env = "0.3.6"
pretty_assertions = "1.4.1"

[features]
## Enable the generation and parsing of a config
build = ["dep:serde","dep:serde_json"]

## The TUI
tui = [
    "dep:clap",
    "dep:crossterm",
    "dep:env_logger",
    "dep:log",
    "dep:ratatui",
    "dep:toml_edit",
    "dep:tui-textarea",
    "dep:walkdir",
    "dep:serde",
    "dep:serde_json",
    "build",
]
